matrix:
    include:
       - language: julia
         julia: 1.0
         os: linux
       - language: julia
         julia: 1.0
         os: osx
       - language: julia
         julia: 1.3
         os: linux
       - language: julia
         julia: 1.3
         os: osx
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("Refactoring")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
